/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumesRouteImport } from './routes/resumes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumesFileIdRouteImport } from './routes/resumes.$fileId'

const ResumesRoute = ResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesFileIdRoute = ResumesFileIdRouteImport.update({
  id: '/$fileId',
  path: '/$fileId',
  getParentRoute: () => ResumesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resumes': typeof ResumesRouteWithChildren
  '/resumes/$fileId': typeof ResumesFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resumes': typeof ResumesRouteWithChildren
  '/resumes/$fileId': typeof ResumesFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resumes': typeof ResumesRouteWithChildren
  '/resumes/$fileId': typeof ResumesFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/resumes' | '/resumes/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/resumes' | '/resumes/$fileId'
  id: '__root__' | '/' | '/resumes' | '/resumes/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumesRoute: typeof ResumesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resumes': {
      id: '/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof ResumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/$fileId': {
      id: '/resumes/$fileId'
      path: '/$fileId'
      fullPath: '/resumes/$fileId'
      preLoaderRoute: typeof ResumesFileIdRouteImport
      parentRoute: typeof ResumesRoute
    }
  }
}

interface ResumesRouteChildren {
  ResumesFileIdRoute: typeof ResumesFileIdRoute
}

const ResumesRouteChildren: ResumesRouteChildren = {
  ResumesFileIdRoute: ResumesFileIdRoute,
}

const ResumesRouteWithChildren =
  ResumesRoute._addFileChildren(ResumesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumesRoute: ResumesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
